### PR TITLE
week-9 api homework

### PR DESCRIPTION
**Pull request by Jessie1128**
http://3.228.79.76:3000/api/attraction/1
http://3.228.79.76:3000/api/attractions
http://3.228.79.76:3000/api/attractions?keyword=溫泉
http://3.228.79.76:3000/api/attractions?page=0

### CODE REVIEW

**Comment by cwpeng** [comment]
Currently, your server response error in any way. Fix it and leave comment for me to review again.

**Comment by Jessie1128** [comment]
老師我剛剛修改了，
再麻煩老師審查了！

**Comment by cwpeng** [comment]
1. use lowercase field names as describing in API spec.
2. "images" field of attraction should be an array contains image URLs separately, not a string.

Fix issues and leave comment for me to review again.

**Comment by Jessie1128** [comment]
1. Changed field names as describing in API to lowercase.

2. Changed "images" field of attraction to an array.

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
